name: Build, Push Docker, and Deploy to Kubernetes

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Container Registry
        uses: docker/login-action@v1
        with:
          registry: docker.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker Image
        run: |
          docker build -t singhritik09/wisecowcontainer1:latest .
          docker push singhritik09/wisecowcontainer1:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install kubectl
        run: |
          curl -LO "https://dl.k8s.io/release/v1.24.0/bin/linux/amd64/kubectl"
          chmod +x ./kubectl
          sudo mv ./kubectl /usr/local/bin/kubectl

      - name: Configure kubectl
        run: |
          echo "${{ secrets.KUBE_CA }}" | base64 --decode > /tmp/ca.crt || { echo "Failed to decode base64"; exit 1; }

          kubectl config set-cluster minikube \
            --server=${{ secrets.KUBE_SERVER }} \
            --certificate-authority=/tmp/ca.crt

          kubectl config set-context minikube \
            --cluster=minikube \
            --user=minikube \
            --namespace=default

          kubectl config use-context minikube
        env:
          KUBE_CA: ${{ secrets.KUBE_CA }}
          KUBE_SERVER: ${{ secrets.KUBE_SERVER }}

      - name: Apply Kubernetes manifests
        run: |
          kubectl apply -f deployment.yaml
          kubectl apply -f service.yaml

      - name: Get Kubernetes resources
        run: |
          kubectl get pods
          kubectl get services

      - name: Port-forward service
        run: |
          kubectl port-forward service/wisecow-service 4499:4499 &
          sleep 10 # Give it time to establish the port-forward
          curl http://localhost:4499 # Test the port-forward
